xnumber_field_settings:
  type: mapping
  label: 'Xnumber field settings'
  mapping:
    step:
      type: string
      label: 'Step'
    min:
      type: string
      label: 'Minimum'
    max:
      type: string
      label: 'Maximum'
    prefix:
      type: label
      label: 'Prefix'
    suffix:
      type: label
      label: 'Suffix'
    placeholder:
      type: label
      label: 'Placeholder'

field.value.xinteger:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'

field.storage_settings.xinteger:
  type: mapping
  label: 'Integer settings'
  mapping:
    unsigned:
      type: boolean
      label: 'Unsigned'
    size:
      type: string
      label: 'The size of a number'

field.field_settings.xinteger:
  type: xnumber_field_settings
  label: 'Integer'

field.value.xdecimal:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'

field.storage_settings.xdecimal:
  type: mapping
  label: 'Decimal settings'
  mapping:
    unsigned:
      type: boolean
      label: 'Unsigned'
    precision:
      type: integer
      label: 'Precision'
    scale:
      type: integer
      label: 'Scale'

field.field_settings.xdecimal:
  type: xnumber_field_settings
  label: 'Decimal settings'


field.value.xfloat:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'

field.storage_settings.xfloat:
  type: mapping
  label: 'Float settings'
  mapping:
    unsigned:
      type: boolean
      label: 'Unsigned'

field.field_settings.xfloat:
  type: xnumber_field_settings
  label: 'Float settings'

xnumber_field_widget_settings:
  type: xnumber_field_settings
  label: 'Xnumber widget settings'
  mapping:
    default_value:
      type: string
      label: 'Default value'
    # This is required by commerce_xquantity module
    disable_on_cart:
      type: string
      label: 'Disable on cart page'

field.widget.settings.xnumber:
  type: xnumber_field_widget_settings
  label: 'Xnumber default display format settings'
