action.configuration.variation_xquantity_stock_adjust:
  type: action_configuration_default
  label: 'Configuration for the Adjust stock action'
action.configuration.variation_xquantity_stock_set:
  type: action_configuration_default
  label: 'Configuration for the Set stock action'
action.configuration.variation_xquantity_stock_rotate:
  type: action_configuration_default
  label: 'Configuration for the Rotate stock action'
